### ISSUE TITLE
Update instance bug

### ISSUE THREAD

**Issue by mieel** [stacklio/stackl#257]
## Steps To Reproduce
stackl apply  on an existing instance

## Actual Result
```
Traceback (most recent call last):
  File "/usr/local/bin/stackl", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/commands/apply.py", line 34, in apply
    apply_stack_instance(config_file, params, tags, secrets,
  File "/usr/local/lib/python3.9/site-packages/commands/apply.py", line 93, in apply_stack_instance
    res = stackl_context.stack_instances_api.put_stack_instance(invocation)
  File "/usr/local/lib/python3.9/site-packages/stackl_client/api_client.py", line 771, in __call__
    return self.callable(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/stackl_client/api/stack_instances_api.py", line 575, in __put_stack_instance
    return self.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/stackl_client/api_client.py", line 818, in call_with_http_info
    self.__validate_inputs(kwargs)
  File "/usr/local/lib/python3.9/site-packages/stackl_client/api_client.py", line 712, in __validate_inputs
    fixed_val = validate_and_convert_types(
  File "/usr/local/lib/python3.9/site-packages/stackl_client/model_utils.py", line 1394, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.9/site-packages/stackl_client/model_utils.py", line 1276, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes,
stackl_client.exceptions.ApiTypeError: Invalid type for variable 'stack_instance_update'. Required value type is StackInstanceUpdate and passed type was StackInstanceInvocation at ['stack_instance_update']
```

# Potential Causes, Fixes or Additional Information

**Comment by GBrawl** [comment]
I'm closing this because it is already fixed, stay tuned for the next release
